version: '3.8'

services:
  film_bot:
    build: .
    container_name: film_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./films.json:/app/films.json
      - ./stats.json:/app/stats.json
    environment:
      - BOT_TOKEN= 
    dns:
      - 8.8.8.8
      - 8.8.4.4
